apiVersion: skaffold/v2alpha3
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: cloudWebApp/auction-website-auth
      context: services/auth
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: cloudWebApp/auction-website-listings
      context: services/listings
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: cloudWebApp/auction-website-bid
      context: services/bid
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: cloudWebApp/auction-website-expiration
      context: services/expiration
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: cloudWebApp/auction-website-profile
      context: services/profile
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: cloudWebApp/auction-website-frontend
      context: services/frontend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: cloudWebApp/auction-website-email
      context: services/email
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.tsx'
          - '**/*.ts'
          - '**/*.js'
    - image: cloudWebApp/auction-website-payments
      context: services/payments
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
deploy:
  kubectl:
    manifests:
      - ./k8s/*
