apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: listings-mysql-pvc
  namespace: auction-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listings-mysql-depl
  namespace: auction-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listings-mysql
  template:
    metadata:
      labels:
        app: listings-mysql
        tier: infrastructure
    spec:
      containers:
        - name: listings-mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "listings"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: listings-mysql-storage
              mountPath: /var/lib/mysql
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -u
                - root
                - -ppassword
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -u
                - root
                - -ppassword
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: listings-mysql-storage
          persistentVolumeClaim:
            claimName: listings-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: listings-mysql-srv
  namespace: auction-system
spec:
  selector:
    app: listings-mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
