apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-depl
  namespace: auction-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
        tier: application
    spec:
      containers:
        - name: email
          image: auction-email:latest
          imagePullPolicy: Never  # For local Minikube images
          env:
            - name: PORT
              value: "3106"
            - name: NODE_ENV
              value: "development"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: "nats://nats-streaming-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "auction"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: EMAIL
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: EMAIL_PASSWORD
          ports:
            - containerPort: 3106
          livenessProbe:
            httpGet:
              path: /api/email/health
              port: 3106
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/email/health
              port: 3106
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: email-srv
  namespace: auction-system
spec:
  selector:
    app: email
  ports:
    - name: email
      protocol: TCP
      port: 3106
      targetPort: 3106
