apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
  namespace: auction-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
        tier: application
    spec:
      containers:
        - name: expiration
          image: auction-expiration:latest
          imagePullPolicy: Never  # For local Minikube images
          env:
            - name: PORT
              value: "3107"
            - name: NODE_ENV
              value: "development"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: "nats://nats-streaming-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "auction"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: "redis-srv"
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 3107
          livenessProbe:
            httpGet:
              path: /api/expiration/health
              port: 3107
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/expiration/health
              port: 3107
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-srv
  namespace: auction-system
spec:
  selector:
    app: expiration
  ports:
    - name: expiration
      protocol: TCP
      port: 3107
      targetPort: 3107
